services:
  my-python-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    environment:
      - postgres=postgres
      - FLASK_APP=API.py
    depends_on:
      - postgres
    volumes:
      - ./:/app
 


  postgres:
    image: postgres:13.6
    ports:
      - "5432:5432"
    hostname: postgres
    # volumes:
      # - './pgdata:/var/lib/postgresql/data' # persist data https://stackoverflow.com/a/41650891/3535853
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: misterbauer

      #POSTGRES_USER: user
      #POSTGRES_DB: database-tvnews
      #POSTGRES_PASSWORD: password
